# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:
  dotnet:
    image: dotnet
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8085:80
